/*
 * oas3_go_flutter_exam Employee
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// EmployeeApiService is a service that implents the logic for the EmployeeApiServicer
// This service should implement the business logic for every endpoint for the EmployeeApi API. 
// Include any external packages or services that will be required by this service.
type EmployeeApiService struct {
}

// NewEmployeeApiService creates a default api service
func NewEmployeeApiService() EmployeeApiServicer {
	return &EmployeeApiService{}
}

// GetEmployee - get employee information
func (s *EmployeeApiService) GetEmployee(employeeId string) (interface{}, error) {
	// TODO - update GetEmployee with the required logic for this service method.
	// Add api_employee_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetEmployee' not implemented")
}
